### Part A: Data Preprocessing

##### Step 1: Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

##### Step 2: Importing dataset

In [2]:
dataset = pd.read_csv('Housing_Data.csv')
dataset

Income  House Age  Area Number of Rooms  Area Number of Bedrooms  \
0     79545.45857   5.682861              7.009188                     4.09   
1     79248.64245   6.002900              6.730821                     3.09   
2     61287.06718   5.865890              8.512727                     5.13   
3     63345.24005   7.188236              5.586729                     3.26   
4     59982.19723   5.040555              7.839388                     4.23   
...           ...        ...                   ...                      ...   
4995  60567.94414   7.830362              6.137356                     3.46   
4996  78491.27543   6.999135              6.576763                     4.02   
4997  63390.68689   7.250591              4.805081                     2.13   
4998  68001.33124   5.534388              7.130144                     5.44   
4999  65510.58180   5.992305              6.792336                     4.07   

      Area Population         Price  
0         23086.80050  1.059034e+06  
1         40173.07217  1.505891e+06  
2         36882.15940  1.058988e+06  
3         34310.24283  1.260617e+06  
4         26354.10947  6.309435e+05  
...               ...           ...  
4995      22837.36103  1.060194e+06  
4996      25616.11549  1.482618e+06  
4997      33266.14549  1.030730e+06  
4998      42625.62016  1.198657e+06  
4999      46501.28380  1.298950e+06  

[5000 rows x 6 columns]

##### Step 3: Creating feature vector and DVV

In [3]:
X = dataset.iloc[:,:-1].values
Y = dataset.iloc[:,-1].values

In [4]:
X

array([[7.95454586e+04, 5.68286132e+00, 7.00918814e+00, 4.09000000e+00,
        2.30868005e+04],
       [7.92486424e+04, 6.00289981e+00, 6.73082102e+00, 3.09000000e+00,
        4.01730722e+04],
       [6.12870672e+04, 5.86588984e+00, 8.51272743e+00, 5.13000000e+00,
        3.68821594e+04],
       ...,
       [6.33906869e+04, 7.25059062e+00, 4.80508098e+00, 2.13000000e+00,
        3.32661455e+04],
       [6.80013312e+04, 5.53438842e+00, 7.13014386e+00, 5.44000000e+00,
        4.26256202e+04],
       [6.55105818e+04, 5.99230531e+00, 6.79233610e+00, 4.07000000e+00,
        4.65012838e+04]])

In [5]:
Y

array([1059033.558, 1505890.915, 1058987.988, ..., 1030729.583,
       1198656.872, 1298950.48 ])

##### Step 4: Replacing missing data

In [6]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean')
imputer.fit(X[:,:])
X[:,:] = imputer.transform(X[:,:])

##### Step 5: Encoding(Not Required)

##### Step 6: Splitting of dataset into training and testing

In [7]:
from sklearn.model_selection import train_test_split
Xtrain,Xtest,Ytrain,Ytest = train_test_split(X,Y,test_size=0.2,random_state=1)

##### Step 7: Feature Scaling(Not Required)

### Part B: Building multiple linear regression model

##### Step 1: Training the linear model

In [8]:
from sklearn.linear_model import LinearRegression
LR = LinearRegression()
LR.fit(Xtrain,Ytrain)

LinearRegression()

##### Step 2: Testing the linear model

In [9]:
Yestimate = LR.predict(Xtest)

In [10]:
print(Yestimate)

[1554219.15762201 1582983.38785289  941849.34310379  943752.69950731
 1183410.51031806  330129.92093548 1927632.211896   1069922.75406542
 1648778.05618106 1073503.34522897  626617.70406749 1538963.80618588
 1631224.3775097  1054158.78454098  961171.82965128 1234681.84681195
 1428653.88192768  925913.80226775 1128251.4977571  1159562.12635957
 1296553.35384097 1865297.38766111 1183231.40915389 1190862.36427287
 1557482.81715817 1862543.1305805   814308.00880999 1063737.59178206
 1226259.21081066  661221.03377596  843011.58134936 1636180.75120879
  665986.95406144 1117105.96878449  800237.32655297 1304234.70596081
 1147460.64721371 1349717.51018746 1034432.05415934 1162747.68744768
 1413050.18421859 1309555.41911966 1576626.16951884 1300214.7568812
  848763.75142766  924167.81958803 1229362.35989915 1161822.48798862
 1422081.71554101 1334121.39586392 1571121.62994742  747837.45566804
  756756.12377102 1036926.24986545 1232318.03872198 1310197.28867453
 1542384.4855388  1074886.84081345 

In [11]:
Yestimate.reshape(len(Yestimate),1)

array([[1554219.15762201],
       [1582983.38785289],
       [ 941849.34310379],
       [ 943752.69950731],
       [1183410.51031806],
       [ 330129.92093548],
       [1927632.211896  ],
       [1069922.75406542],
       [1648778.05618106],
       [1073503.34522897],
       [ 626617.70406749],
       [1538963.80618588],
       [1631224.3775097 ],
       [1054158.78454098],
       [ 961171.82965128],
       [1234681.84681195],
       [1428653.88192768],
       [ 925913.80226775],
       [1128251.4977571 ],
       [1159562.12635957],
       [1296553.35384097],
       [1865297.38766111],
       [1183231.40915389],
       [1190862.36427287],
       [1557482.81715817],
       [1862543.1305805 ],
       [ 814308.00880999],
       [1063737.59178206],
       [1226259.21081066],
       [ 661221.03377596],
       [ 843011.58134936],
       [1636180.75120879],
       [ 665986.95406144],
       [1117105.96878449],
       [ 800237.32655297],
       [1304234.70596081],
       [1147460.64721371],
 

In [12]:
Ytest.reshape(len(Ytest),1)

array([[1413579.817  ],
       [1618721.138  ],
       [ 841392.493  ],
       [ 881443.9247 ],
       [1174747.551  ],
       [ 266298.8811 ],
       [1877941.971  ],
       [1022408.901  ],
       [1766248.403  ],
       [ 949072.2496 ],
       [ 565937.2006 ],
       [1437153.959  ],
       [1582605.535  ],
       [1009854.705  ],
       [1116351.753  ],
       [1255736.409  ],
       [1504441.01   ],
       [ 837540.1697 ],
       [1096069.287  ],
       [1205962.995  ],
       [1130844.029  ],
       [1815920.45   ],
       [1023595.113  ],
       [1054304.172  ],
       [1399909.049  ],
       [1710612.03   ],
       [ 670063.0223 ],
       [1245785.051  ],
       [1168760.428  ],
       [ 412269.2034 ],
       [ 677988.2555 ],
       [1715435.991  ],
       [ 662630.3439 ],
       [1167449.99   ],
       [ 714706.4289 ],
       [1411217.493  ],
       [1200125.447  ],
       [1322439.108  ],
       [1127637.557  ],
       [1066040.789  ],
       [1383842.185  ],
       [1364306.

In [13]:
np.concatenate((Yestimate.reshape(len(Yestimate),1),Ytest.reshape(len(Ytest),1)),1)

array([[1554219.15762201, 1413579.817     ],
       [1582983.38785289, 1618721.138     ],
       [ 941849.34310379,  841392.493     ],
       ...,
       [1717971.58093465, 1644923.078     ],
       [1007962.88533644, 1106336.838     ],
       [ 829010.93814412,  759044.688     ]])

###### Coefficients of the regression

In [14]:
LR.coef_

array([2.16667346e+01, 1.64990052e+05, 1.20784238e+05, 1.54252467e+03,
       1.51503697e+01])

In [15]:
LR.intercept_

-2637185.6400935473